#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 7 -xoffset 14 -yoffset -52 -line-padding 4 -columns 1 -width 30 -lines 10 -padding 20 -hide-scrollbar -show-icons -drun-icon-theme -theme arthur
